### ISSUE TITLE
Installation stall

### ISSUE THREAD

**Issue by cherrytree456** [clarype/al_zonal_stats#1] opened 2022-12-07 17:16 UTC
During the installation of PyEnvs-0.5-Windows-x86_64.exe, it hangs up at the end 'setting up package cache' and will not finish the install. See screenshot. 
![install_not_responding](https://user-images.githubusercontent.com/36208703/206245773-74c3e249-4853-40d9-a95b-4005e37b11c2.jpg)

I've tried installing in c:\temp\ and c:\users\mymusername\documents\. If I 'force quit' the installation before it's successful, this is what I receive when I run Start_PyEnv.bat
![image](https://user-images.githubusercontent.com/36208703/206246209-4804a402-0912-4891-a4df-628c4e908c5d.png)

**Comment by clarype** [comment] 2022-12-07 20:38
One thing that comes to mind is permissions. So I would try installing it in a place like Documents or an external hard drive. If it does install on an external hard drive you can either run it from there or copy the installed directory to your local disk.  Just make sure the BAT file points to it.

**Comment by clarype** [comment] 2022-12-13 22:34
The commenter was able to install the application but I was unable to reproduce the error. so I am closing this issue as not reproducible

**Closed as not planned** 2022-12-13 22:34 UTC
